-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 7.5
-- Thu Jun 09 21:21:40 2022

-- parameterized module component declaration
component memEBR00
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(5 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : memEBR00
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(5 downto 0)=>__, 
        Data(7 downto 0)=>__, Q(7 downto 0)=>__);
